### ISSUE TITLE
iptables v1.6.0: invalid port/service `-j' specified

### ISSUE THREAD

**Issue by jsindy** [jawj/IKEv2-setup#1]
Getting this error on google compute engine. Ubuntu 16.10 image.

iptables v1.6.0: invalid port/service `-j' specified
Try `iptables -h' or 'iptables --help' for more information.

**Comment by jawj** [comment]
I suspect this is happening because an environment variable is empty. Candidates could be SSHPORT (did you make sure to fill that in when prompted?) or ETH0ORSIMILAR (which would be down to my detection method for the main Internet interface not working on Google).

Afraid I haven't got time at present to investigate (which would mean trying to set up on Google myself), but please do post if you figure out how to resolve this.

The script is tested so far on Linode and OVH.

**Comment by jsindy** [comment]
GCE uses ENS# instead of ETH#. That was the issue.

**Comment by jawj** [comment]
Ah, thanks. 

Were you using the latest version of the script? 

It now tries to detect the interface name, like this: `ETH0ORSIMILAR=$(ip route get 8.8.8.8 | awk -- '{printf $5}')`.

So I wonder if this is working correctly ...
