### ISSUE TITLE
Certificate is Not Signed (iOS)

### ISSUE THREAD

**Issue by romatou** [jawj/IKEv2-setup#149]
I installed this IKEv2 config with the following command:
```
wget https://raw.githubusercontent.com/jawj/IKEv2-setup/master/setup.sh
chmod u+x setup.sh
./setup.sh
```
Then copied the `ios.mobileconfig` to iPhone, installed it. Everything is working fine, but how can I fix the **Not Signed** problem?

![IMG_8A4B9733F9F6-1](https://user-images.githubusercontent.com/49362229/202700197-065fc72d-4302-40aa-9b6a-878f38f5369d.jpeg)

**Comment by jawj** [comment]
First, the problem is just that it says 'Not Signed' in red text — it still works, right?

It is actually possible to sign the profile using the same Let's Encrypt certificate we use to identify the server to the VPN client. The issue is, these certificates have a 3 month expiry, so the profile becomes unsigned again pretty fast.
