### ISSUE TITLE
Strongswan: no private key found.  Windows 10: error 13801

### ISSUE THREAD

**Issue by Lord-Dimwit-Flathead-the-Excessive** [jawj/IKEv2-setup#159]
Thanks for the setup.sh script - did not use directly but great roadmap.  However ... 

Private key in /etc/ipsec.secrets is configured to be read RSA. 
`
echo "${VPNHOST} : RSA \"privkey.pem\"
${VPNUSERNAME} : EAP \"${VPNPASSWORD}\"
" > /etc/ipsec.secrets
`
But certbot acquires ECDSA encrypted keys by default apparently.  Perhaps adding `--key-type rsa` to:

`
certbot certonly --non-interactive --agree-tos --standalone --preferred-challenges http --email "${EMAILADDR}" -d "${VPNHOST}"
`

See [serverfault](https://serverfault.com/questions/1151269/strongswan-vpn-from-windows-10-no-private-key-found-13801) for details.

**Comment by tobiasbrunner** [comment]
This happens because the default key type changed when `certbot` acquires certificates. So as an alternative to changing this line in `ipsec.secrets`, the key type could explicitly be specified when calling `certbot` via `--key-type rsa`. Using RSA might be necessary anyway at the moment because iOS/macOS clients currently have issues with ECDSA server certificates.

Also note that switching to [swanctl.conf](https://docs.strongswan.org/docs/5.9/swanctl/swanctlConf.html) would allow loading arbitrary private keys by placing them in [`/etc/swanctl/private`](https://docs.strongswan.org/docs/5.9/swanctl/swanctlDir.html) (simplifies the server config, clients might still not like ECDSA keys).

**Comment by Lord-Dimwit-Flathead-the-Excessive** [comment]
Sounds like you are on top of it.  Thanks.

**Comment by tobiasbrunner** [comment]
I'm not involved with this project, so I don't think this should be closed as either of the two fixes are required for the script to be usable.

**Comment by jawj** [comment]
Thanks both for your help. Hopefully this sorts it out.

**Comment by jawj** [comment]
@tobiasbrunner While you're here ... it appears to me as if recent macOS sometimes disregards the ciphers set in the `.mobileconfig` file, and proposes only weaker ones. Then the connection fails and I see this in `/var/log/syslog`:

```
Jan 12 12:53:07 VPN charon: 16[CFG] received proposals: IKE:AES_GCM_16_256/PRF_HMAC_SHA2_256/ECP_256, IKE:AES_GCM_16_256/PRF_HMAC_SHA2_256/MODP_2048, IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256, IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Jan 12 12:53:07 VPN charon: 16[CFG] configured proposals: IKE:AES_GCM_16_256/PRF_HMAC_SHA2_384/ECP_384
Jan 12 12:53:07 VPN charon: 16[IKE] remote host is behind NAT
Jan 12 12:53:07 VPN charon: 16[IKE] received proposals unacceptable
```

I can fix this (at the cost of lower security) by adding the proposed variants, `prfsha256` and `ecp256`, to `ipsec.conf`:

```
ike=aes256gcm16-prfsha384-ecp384,aes256gcm16-prfsha256-ecp256!
```

But I just wondered if you were aware/could confirm this issue, or know of any better workaround?

**Comment by tobiasbrunner** [comment]
No, wasn't aware of this. Does this happen during an initial connection attempt? Or during rekeying or reauthentication of an existing IKE_SA? Either way, it should probably be reported to Apple.

**Comment by jawj** [comment]
@tobiasbrunner Thanks. I haven't had a chance to fully characterise it, but:

* It happens during the initial connection attempt.
* Oddly, I don't think it happens during the _first ever_ connection attempt, or maybe the first since a reboot.

As I write, the VPN just disconnected unexpectedly and I saw this in the log, which maybe addresses your rekeying query:

```
Jan 12 13:41:22 VPN ipsec[612]: 10[ENC] parsed CREATE_CHILD_SA request 9 [ N(REKEY_SA) SA No KE TSi TSr ]
Jan 12 13:41:22 VPN ipsec[612]: 10[CFG] received proposals: ESP:AES_GCM_16_256/ECP_256/NO_EXT_SEQ, ESP:AES_GCM_16_256/MODP_2048/NO_EXT_SEQ, ESP:AES_GCM_16_256/NO_EXT_SEQ
Jan 12 13:41:22 VPN ipsec[612]: 10[CFG] configured proposals: ESP:AES_GCM_16_256/ECP_384/NO_EXT_SEQ
Jan 12 13:41:22 VPN ipsec[612]: 10[IKE] no acceptable proposal found
```

Guess I'll report all this on Apple's Feedback Assistant.

**Comment by tobiasbrunner** [comment]
> As I write, the VPN just disconnected unexpectedly and I saw this in the log, which maybe addresses your rekeying query:

Yes, that's the rekeying of a CHILD_SA (REKEY_SA notify in a CREATE_CHILD_SA exchange, also the ESP proposals). While the previous log was from an IKE_SA (re-)creation (IKE proposal and NAT detection, the latter wouldn't be seen during an IKE_SA rekeying). Definitely weird that it happens in so many different situations.

> Guess I'll report all this on Apple's Feedback Assistant.

Yeah, there isn't really anything the server can do other than accept the weaker proposal.
