### ISSUE TITLE
Public CA, a good idea?

### ISSUE THREAD

**Issue by SquirrelCoder** [jawj/IKEv2-setup#27]
Hi,

Thanks  a lot for this great script. 
I was wondering, if using a Public CA (Let's Encrypt) for certificates would be wise?
Isn't it better and more secure if we self-signed the certs?
I am not sure if this comment in this -> [https://serverfault.com/a/763694](url) question is technically right or not, but if it is, then a self-signed cert would be a lot better.

Thanks.

**Comment by jawj** [comment]
Signing your own certificates can be theoretically more secure, because you're immune from attacks where a bad actor gets a certificate issued for your domain and then manipulates DNS somehow to MITM you. But it can also be a significantly bigger faff when setting up the clients. Public CA is the right trade-off for me. Private CA seems to be the norm with VPNs, so you'll find plenty of tutorials if you want to go that way instead.

**Comment by SquirrelCoder** [comment]
Hey sorry man, I have another question too.

Could you please tell me, what's the purpose of this line?
`ln -f -s /etc/ssl/certs/DST_Root_CA_X3.pem /etc/ipsec.d/cacerts/`
The VPN connects perfectly even without this link!

Thanks a lot.
