### ISSUE TITLE
Apache2 is not accessible from outside world after StrongSwan installed

### ISSUE THREAD

**Issue by Bougakov** [jawj/IKEv2-setup#43]
Hi. I found a curious problem.
I have clean Ubuntu 17 image on DigitalOcean, where I installed StrongSwan. It works nicely.
I also installed Apache2 and enabled it in the UFW.

Problem is that I can't access it from my browser - not by IP, not by hostname. SSH to machine works, VPN clients connect, but not HTTP. If I wget' my hostname or IP on the local terminal (in SSH), I am able to receive contents of my test index.html, so it is certainly not Apache's problem, but firewall's.

It is certainly an issue with the way the script has configured firewall rules, but I can't figure it out. Please point me in the right direction.

**Comment by TheyCantHandle** [comment]
On which port is configured your vpn? Is it on same port as Apache2? Usually you cannot share same port from apache2 (80/443 —> http/https) to other services such as VPN. So the reason why you cannot access your VPN in your browser is because these 2 services are conflicting each other. So either you find a way in your vpn setup to share the same port (some vpn config have an option for that) or you use a different port for your vpn and when you want to access it from browser you specify the port (ex: 0.0.0.0:25 where 0.0.0.0 is your IP address and :25 is the port specified)

**Comment by Fastidious** [comment]
@TheyCantHandle `IKEv2-setup` doesn't configure anything on ports `80` or `443` (it opens port `443` to configure SSL, but that's  about it).

**Comment by TylerAndrew** [comment]
[this helped me maybe it'll help you?](https://askubuntu.com/questions/950470/virtualbox-ubuntu-17-04-cannot-connect-to-the-internet)

**Comment by Bougakov** [comment]
Figured it out - setup script adds: https://github.com/jawj/IKEv2-setup/blob/475eabb5c8cf08bad68496034da5491edf45b226/setup.sh#L159 that discards all new iptables rules that are added later when configuring Apache. Probably, setup script needs to ask whether the user wants to 'harden' the setup this way or s/he intends to add some more components later.
