### ISSUE TITLE
*.mobileconfig not emailed : where to find?

### ISSUE THREAD

**Issue by michaeljameslewis** [jawj/IKEv2-setup#62]
Awesome script!  Worked perfectly on Ubuntu 18.04 + Digital Ocean.

Already had strongSwan on my Android, and it connected immediately, without any issues.

One thing: Never received an email with *.mobileconfig

Tried to find, no results.

Copied text from setup.sh to a new file to manually write a .mobileconfig (replacing vars with hostname), but fails on import with:
"Invalid profile: The PayloadUUID “$(uuidgen)” is used more than once in the profile."

Is it safe to re-run setup.sh ? Otherwise, where would I find the .mobileconfig file it was supposed to have written?

Thanks!

**Comment by jawj** [comment]
It's safe to run the script again, but it will ask you for all the info again.

Your configuration files should be saved in /home/[username], where [username] is the login username you chose.

I switched the mail sending from mailutils to mutt last week because of problems I was seeing. Hopefully the issue was with spam filters rather than the actual sending of the mail.

**Comment by jawj** [comment]
Otherwise you just need to replace `$(uuidgen)` with the output of the `uuidgen` command, run afresh each time.
